if(NOT DEFINED INPUTS OR NOT DEFINED LOGICAL_PATHS OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "write_sha256_manifest.cmake requires INPUTS, LOGICAL_PATHS, and OUTPUT")
endif()

list(LENGTH INPUTS INPUT_COUNT)
list(LENGTH LOGICAL_PATHS LOGICAL_PATH_COUNT)
if(NOT INPUT_COUNT EQUAL LOGICAL_PATH_COUNT OR INPUT_COUNT EQUAL 0)
    message(FATAL_ERROR "SHA-256 manifest input and logical-path lists must be nonempty and equal")
endif()

set(MANIFEST "{\n  \"schema\": \"trinity.generated-resource-manifest.v1\",\n  \"resources\": [\n")
math(EXPR LAST_INDEX "${INPUT_COUNT} - 1")
foreach(INDEX RANGE ${LAST_INDEX})
    list(GET INPUTS ${INDEX} INPUT)
    list(GET LOGICAL_PATHS ${INDEX} LOGICAL_PATH)
    if(NOT EXISTS "${INPUT}")
        message(FATAL_ERROR "Manifest input does not exist: ${INPUT}")
    endif()
    file(SHA256 "${INPUT}" INPUT_SHA256)
    string(APPEND MANIFEST
        "    {\"logicalPath\": \"${LOGICAL_PATH}\", \"sha256\": \"${INPUT_SHA256}\"}")
    if(NOT INDEX EQUAL LAST_INDEX)
        string(APPEND MANIFEST ",")
    endif()
    string(APPEND MANIFEST "\n")
endforeach()
string(APPEND MANIFEST "  ]\n}\n")
file(WRITE "${OUTPUT}" "${MANIFEST}")
